# Numpy Module
> Stands for *Numerical Python*.  
> **Numpy** is an n dimensional object or ndarray.  
> Provides an efficient way of storing *homogenous* data.  
> We can have ndarray with 1 dim or 1 row.
> We can have multi-dim arrays with more than one row $[[row1a,rowab],[row2a,row2b]]$.

## Rank 1 array

In [46]:
a1 = [1,2,3,4,5]
print(type(a1))

<class 'list'>


In [47]:
import numpy as np
n1 = np.array(a1)
type(n1)

numpy.ndarray

## Slicing 

In [48]:
a=[1,2,11,6,8,18,2]
na=np.array(a)

In [49]:
na[2]

11

In [50]:
na[1:5]

array([ 2, 11,  6,  8])

In [51]:
na[1:5:2]

array([2, 6])

## Multidimensional array

In [52]:
a2 = [[1,2,3],[4,5,6]]
n2 = np.array(a2)
print(n2.shape)

(2, 3)


In [53]:
z1 = np.zeros((2,2))
z1

array([[0., 0.],
       [0., 0.]])

In [54]:
z2 = np.zeros((2,2),dtype=int)
z2

array([[0, 0],
       [0, 0]])

In [55]:
f1=np.full((2,2),5)
f1

array([[5, 5],
       [5, 5]])

In [56]:
i1 = np.eye(2,2) #diagonal 1
print(i1)

[[1. 0.]
 [0. 1.]]


In [57]:
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]
narr=np.array(arr)
print (narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [58]:
print(narr[0])

[1 2 3 4]


In [59]:
print(narr[2])

[7 8 9 6]


In [60]:
print(narr[2,3])

6


## Concatenate

In [61]:
x=np.array([2,6,8,4])
y=np.array([11,8,2])
z=np.concatenate([x,y])
z

array([ 2,  6,  8,  4, 11,  8,  2])

In [62]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c=np.concatenate([a, b])

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Arithmetic Operation on Numpy Objects

In [63]:
#create numpy arrays
x = np.array([1,2,3])
y = np.array([2,3,4])

In [64]:
x+y

array([3, 5, 7])

In [65]:
print(x*3)

[3 6 9]


In [66]:
# Hadmard product
x*y

array([ 2,  6, 12])

In [67]:
# Dot product (Multiply then Sum)
print(np.dot(y,x))

20


In [68]:
A=np.matrix([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [69]:
# Haddmard multiplication
print (A*A)

[[ 7 10]
 [15 22]]


In [70]:
# Elemant wise multiplication
print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


In [71]:
# Inverse of Matrix
from numpy.linalg import inv
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [72]:
# Transpose of Matrix
print(A.T)

[[1 3]
 [2 4]]


## Solving x for equation Ax=b

In [73]:
A=np.array([[2,1],[1,-1]])
print(A)

b=np.array([4,-1])
print(b)

np.linalg.solve(A,b)

[[ 2  1]
 [ 1 -1]]
[ 4 -1]


array([1., 2.])

## Basic Statistics with numpy

In [74]:
arr = [[1,2,3,4],[3,4,5,6],[7,8,9,6],[2,11,8,10]]
narr = np.array(arr)
print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [ 2 11  8 10]]


In [75]:
narr.sum()

89

In [76]:
narr.sum(axis=0) # column wise sum

array([13, 25, 25, 26])

In [77]:
narr.sum(axis=1) # row wise sum

array([10, 18, 30, 31])

In [78]:
narr.mean(axis=0)

array([3.25, 6.25, 6.25, 6.5 ])

In [79]:
np.mean(narr,axis=0)

array([3.25, 6.25, 6.25, 6.5 ])

In [80]:
narr.std(axis=0)

array([2.27760839, 3.49106001, 2.384848  , 2.17944947])

In [81]:
np.median(narr,axis=1)

array([2.5, 4.5, 7.5, 9. ])

In [82]:
np.percentile(narr,50,axis=1)

array([2.5, 4.5, 7.5, 9. ])

In [130]:
np.sqrt(5)

2.23606797749979

In [131]:
np.exp(2)

7.38905609893065

In [132]:
e = np.exp(1)
np.log(e)

1.0

In [133]:
n = 10
np.log10(n)

1.0

In [134]:
np.abs(-10)

10

## Random Number Generators

In [85]:
np.random.normal(10,5,20) # Normal (mean,std,size)

array([11.21821835,  4.15018512,  6.29994351,  9.64159791,  9.93544659,
        8.5295252 ,  3.95868568,  6.07493147,  9.5067843 ,  9.73823716,
       10.12666562, 16.07729925, 13.10266484, 13.65349565,  8.66076598,
       10.05704068, 11.00197199,  5.88453621,  6.4054133 , 14.91845491])

In [86]:
np.random.rand(2,4) # Uniform (dimension1, dimension2)

array([[0.40342634, 0.31950413, 0.99172814, 0.27450726],
       [0.83293562, 0.71817792, 0.89133564, 0.66461932]])

In [87]:
np.random.randn(2,4) # Standard Normal (dimension1, dimension2)

array([[ 0.43967655,  0.90876368, -0.70342473, -2.18632196],
       [ 0.24598769,  0.59512664,  0.34362738,  0.6422377 ]])

In [88]:
np.random.seed(1234) # Choice of seed that generates the random numbers
np.random.normal(10,5,20)

array([12.35717582,  4.04512153, 17.16353484,  8.43674052,  6.39705633,
       14.4358147 , 14.29794207,  6.81738248, 10.07848186, -1.21342477,
       15.75017862, 14.95973011, 14.76662064, -0.1062741 ,  8.32961317,
       10.01059182, 12.02726706, 11.4454597 , 16.60579096,  2.26547223])

In [89]:
np.random.seed(1234) # Same as above
np.random.normal(10,5,20)

array([12.35717582,  4.04512153, 17.16353484,  8.43674052,  6.39705633,
       14.4358147 , 14.29794207,  6.81738248, 10.07848186, -1.21342477,
       15.75017862, 14.95973011, 14.76662064, -0.1062741 ,  8.32961317,
       10.01059182, 12.02726706, 11.4454597 , 16.60579096,  2.26547223])

## Slicing Again

In [96]:
np.random.seed(123)
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(data)

[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052  -1.4286807 ]]


In [97]:
data[names=='Bob']

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128]])

In [98]:
data[names=='Bob',2:]

array([[ 0.2829785 , -1.50629471],
       [-0.44398196, -0.43435128]])

In [99]:
data[names !='Bob']

array([[-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904],
       [-1.25388067, -0.6377515 ,  0.9071052 , -1.4286807 ]])

In [100]:
data[~(names=='Bob')]

array([[-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904],
       [-1.25388067, -0.6377515 ,  0.9071052 , -1.4286807 ]])

In [112]:
ppl = (names=='Bob')|(names=='Will')
ppl

array([ True, False,  True,  True,  True, False, False])

In [113]:
data[ppl]

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ]])

In [115]:
# Replace all negative values by 0
data[data<0]=0
data

array([[0.        , 0.99734545, 0.2829785 , 0.        ],
       [0.        , 1.65143654, 0.        , 0.        ],
       [1.26593626, 0.        , 0.        , 0.        ],
       [1.49138963, 0.        , 0.        , 0.        ],
       [2.20593008, 2.18678609, 1.0040539 , 0.3861864 ],
       [0.73736858, 1.49073203, 0.        , 1.17582904],
       [0.        , 0.        , 0.9071052 , 0.        ]])

## Reshape the Array

In [117]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
a = arr.reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [128]:
b = arr.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [129]:
a.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [126]:
b.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## Activity 1
> - Generate an 50x1 array $X$ containing random normals ~ N(0,1).  
> - Calculate the variance of $X$.  
> - Generate another 50x1 array $u$ containing random normals ~ N(0,1).  
> - Generate a y that equals to $y=1+2x+u$.  
> - Calculate the mean and variance of $y$.

## Activity 2
> - Calculate inverse of $(X'X)$.  
> - Calculate covariance of $y$ and $X$.    
> - What is the value of the product of inverse of $(X'X)$ and $cov(X,y)$?    