# Data Manipulation with Pandas
> **Pandas** is built on top of **Numpy**.  
> It provides an efficient implementation of a ***DataFrame*** and ***Series***.   

In [1]:
import pandas as pd

## Pandas Series
> - The **values** are implicitly **indexed**  

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [3]:
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


### Slicing Pandas Series
> - Based on their **implicit index**

In [5]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


### Pandas Series 
> - Based on **explicitly defined index**.

In [40]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [43]:
print(data['b'])
print(data['a':'c'])

0.5
a    0.25
b    0.50
c    0.75
dtype: float64


In [20]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [23]:
# When a series is explicity indexed, 
# the slicing number refers explicit index (not implicit)
# Later on, you will learn how to use loc and iloc to subset pandas series
data[3]

0.75

### Series as specialized dictionary
> - Recall **dictionary** has keys and values  
> - **dictionary** can be transformed to **pandas series**  

In [24]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [78]:
print(population_dict.keys()) # Dictionary-way to call the index
print(population.index)       # pd.Series-way 1 to call the index
print(population.keys())      # pd.Series-way 2 to call the index

dict_keys(['California', 'Texas', 'New York', 'Florida', 'Illinois'])
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')


In [79]:
print(population_dict.values())  # Dictionary-way to call the values
print(population.values)         # pd.Series-way to call the values

dict_values([38332521, 26448193, 19651127, 19552860, 12882135])
[38332521 26448193 19651127 19552860 12882135]


TypeError: 'numpy.ndarray' object is not callable

In [35]:
print(population['California'])              # Report values only
print(population['California':'Illinois'])   # Report values with index

38332521
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [46]:
# Create a new dictionary and pandas.Series object
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

In [47]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

### DataFrame as a sequence of aligned Series objects
> - A **DataFrame** contain multiple variables/Series.  
> - **dictionary** can be converted into **pd.DataFrame**.  
> - **numpy arrays** can also be converted into **pd.DataFrame**.  

In [48]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [49]:
print(states.index)    # Rows
print(states.columns)  # Columns

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object')


In [18]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [50]:
# Transform pd.Series into pd.DataFrame
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [53]:
# Transform a list to pd.DataFrame
# i=0,1,2 in the following code
# List contains 3 dictionaries with index 'a' & 'b'
data = [{'a': i, 'b': 2 * i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [55]:
df = pd.DataFrame(data)
df

a  b
0  0  0
1  1  2
2  2  4

In [57]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['a', 'b'], dtype='object')


In [58]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [64]:
# Generate 3x2 numpy arrays ~ uniform distribution.  
# Columns are named as 'foo' & 'bar'
# Rows are named as 'a', 'b', 'c'
# Convert to pd.DataFrame

import numpy as np
pd.DataFrame(np.random.rand(3, 2),columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.449045  0.702320
b  0.788117  0.102369
c  0.957071  0.556170

In [71]:
A = np.zeros((3,2),dtype=int)
pd.DataFrame(A)

0  1
0  0  0
1  0  0
2  0  0

In [72]:
# Create an explict index for pandas objects
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [30]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [73]:
print(ind[1])
print(ind[::2])

3
Int64Index([2, 5, 11], dtype='int64')


In [74]:
# Pandas index is not mutable
ind[1] = 0

TypeError: Index does not support mutable operations

In [75]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [76]:
indA & indB # intersection

Int64Index([3, 5, 7], dtype='int64')

In [34]:
indA | indB # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [35]:
indA ^ indB # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

### More on Pandas Series
> - Index is not mutable but value is  
> - Allow adding new items

In [77]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [83]:
# Although index is not mutable, values can be 
data['d'] = 1.25
list(data.items()) # Same as the dictionary-way of calling items

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.25), ('e', 5.21)]

In [84]:
# Adding new item in pd.Series
data['e'] = 5.21
data

a    0.25
b    0.50
c    0.75
d    1.25
e    5.21
dtype: float64

In [38]:
# Boolean (Checking if index is in data)
'a' in data

True

### Slicing by Explicit Index & Implicit Index
> - Sometimes quite confusing  
> - So, **loc** refers to **explicit index**  
> - **iloc** refers to **implicit index**  

In [85]:
# Explicit index
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [86]:
# Implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [44]:
# Masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [45]:
# Fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [87]:
# Confusion comes when index is numeric
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [47]:
data[1]   # explicit

'a'

In [48]:
data[1:3] # implicit

3    b
5    c
dtype: object

In [88]:
# Explicit index
print(data.loc[1])  
print(data.loc[1:3])

a
1    a
3    b
dtype: object


In [89]:
# Implicit index
print(data.iloc[1]) 
print(data.iloc[1:3])

b
3    b
5    c
dtype: object


In [96]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [97]:
# 2 ways to call the column AREA
print(data['area'])
print('*****')
print(data.area_size)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64
*****


AttributeError: 'DataFrame' object has no attribute 'area_size'

In [56]:
data.area is data['area']

True

In [57]:
# Not work if the column names are not strings, 
# or if the column names conflict with methods of the DataFrame
data.pop is data['pop']

False

In [93]:
# Adding variable to pd.DataFrame
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [59]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [60]:
# Transpose can be done in the same way as numpy
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [94]:
data.values[0] # Implicit index

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [62]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [63]:
data.iloc[:3, :2] # Implicit index

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [64]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [65]:
# Put indices in a list ['index1','index2']
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [95]:
# Values are immutable
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [67]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [68]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# Activity 1
> - Add a **pd.Series** named **Code** to the above data.  
> - **Code** is the state code: California=CA, Texas=TX, NewYork=NY, Florida=FL, Illinois=IL.  
> - Subset data by **Code**: Select TX and NY only.  
> - Solve the naming problem of pop:  
> - Recall that the outcome of the following is ```FALSE```.
```python 
data.pop is data['pop']
``` 